#!/bin/sh
echo "*** starting telegrafh ***"
exec 2>&1
source /data/telegraf/etc/telegraf/.env
exec /data/telegraf/telegraf-1.34.2/usr/bin/telegraf --config /data/telegraf/etc/telegraf/telegraf.conf --config-directory /data/telegraf/etc/telegraf/telegraf.d/