#!/bin/sh
echo "*** starting telegrafh ***"
exec 2>&1
source /data/telegraf/etc/telegraf/.env
# see https://github.com/influxdata/telegraf/pull/16454/files
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-/dev/null}"
exec /data/telegraf/telegraf-1.34.2/usr/bin/telegraf --config /data/telegraf/etc/telegraf/telegraf.conf --config-directory /data/telegraf/etc/telegraf/telegraf.d/